apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: spring
  name: spring
  namespace: default
spec:
  rules:
  - host: misbah.lokal
    http:
      paths:
      - backend:
          serviceName: spring
          servicePort: 80
        path: /
