##################################################
# Configure Common Kubernetes Server Setting
##################################################

- name: Add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Add overlay module
  modprobe:
    name: overlay
    state: present

- name: Persist systemd module on reboot
  template:
    src: "11-kubernetes.conf.j2"
    dest: "/etc/modules-load.d/"
    owner: root
    group: root
    mode: 0644

- name: Enable and run systemd-load-modules service
  systemd:
    name: systemd-modules-load
    enabled: yes
    state: started

- name: Enable ipv4 forwarding, iptable bridge
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/11-kubernetes.conf
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-arptables

- name: Add Kubernetes Repository
  yum_repository:
    name: Kubernetes
    file: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes
    gpgcheck: yes

- name: Install Kubelet, Kubeadm, Kubectl
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable and Run Kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

# - name: Enable firewall masquerade for kubernetes
#   firewalld:
#     masquerade: "yes"
#     permanent: yes
#     immediate: yes
#     state: enabled

# - name: Enable firewall port for kubernetes
#   firewalld:
#     port: "{{ item }}"
#     permanent: yes
#     immediate: yes
#     state: enabled
#   loop:
#     - 443/udp
#     - 6443/tcp
#     - 10250/tcp
#     - 10251/tcp
#     - 10252/tcp
#     - 10255/tcp
#     - 8472/udp
#     - 2379/tcp
#     - 2380/tcp
#     - 4789/udp
#     - 5473/tcp
#     - 179/tcp
